Get http://localhost:3000/users

### Create User Akane
POST http://localhost:3000/users
Content-Type: application/json

  {
  "username": "Akane",
  "email" : "Akane@example.com",
  "password" : "pass123"
}
### Create User Flogal
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Flogal",
  "email" : "Flogal@example.com",
  "password" : "pass123"
}

### Update a user
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "username": "AshaNotZalt",
  "email" : "AshaNotSalt@example.com",
  "password" : "pass123"
}
### Delete a user
DELETE http://localhost:3000/users/1