Get http://localhost:3000/api/v2/users

### Create User Akane
POST http://localhost:3000/api/v2/users
Content-Type: application/json

  {
  "username": "Akane",
  "email" : "Akane@example.com",
  "password" : "pass123567"
}
### Create User Flogal
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
  "username": "Flogal",
  "email" : "Flogal@example.com",
  "password" : "pass123567"
}
### Create User SoulSaverDragon
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
  "username": "SoulSaverDragon",
  "email" : "SoulSaverDragon@example.com",
  "password" : "pass123567"
}

### Update a user
PUT http://localhost:3000/api/v2/users/6a0d67d6e977a62d3ad55b9b
Content-Type: application/json

{
  "username": "AshaNotZalt",
  "email" : "AshaNotSalt@example.com",
  "password" : "pass123567"
}
### Delete a user
DELETE http://localhost:3000/api/v2/users/6a0d67d6e977a62d3ad55b9b

### Login user
POST http://localhost:3000/api/v2/users/login
Content-Type: application/json

{
  "email": "akane@example.com",
  "password": "pass123567"
}

### ตรวจสอบข้อมูลผู้ใช้ปัจจุบัน (ต้องผ่าน Middleware authUser)
GET http://localhost:3000/api/v2/users/auth/me

### Logout user
POST http://localhost:3000/api/v2/users/auth/logout