Get http://localhost:3000/api/v2/users

### Create User Akane
POST http://localhost:3000/api/v2/users
Content-Type: application/json

  {
  "username": "Akane",
  "email" : "Akane@example.com",
  "password" : "pass123567"
}
### Create User Flogal
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
  "username": "Flogal",
  "email" : "Flogal@example.com",
  "password" : "pass123567"
}

### Update a user
PUT http://localhost:3000/api/v2/users/6a0be5d09a59c157896ca9b2
Content-Type: application/json

{
  "username": "AshaNotZalt",
  "email" : "AshaNotSalt@example.com",
  "password" : "pass123567"
}
### Delete a user
DELETE http://localhost:3000/api/v2/users/6a0d4106cbb2d40c3ca5a677

### Login user
POST http://localhost:3000/api/v2/auth/login
Content-Type: application/json

{
  "email": "akane@example.com",
  "password": "pass123567"
}